

export const GET_PRODUCTOS = 'GET_PRODUCTOS'
export const ADD_PRODUCTO = 'ADD_PRODUCTO'
export const POLL_PRODUCTOS = 'POLL_PRODUCTOS'
export const ACTUALIZAR_EXISTENCIA = 'ACTUALIZAR_EXISTENCIA'

export const SET_ORDEN = 'SET_ORDEN'
export const GET_ORDENES = 'GET_ORDENES'
export const GET_NEW_ORDENES = 'GET_NEW_ORDENES'
// export const OBTENER_USUARIO = 'OBTENER_USUARIO'
// export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
// export const LOGIN_ERROR = 'LOGIN_ERROR'
// export const CERRAR_SESION = 'CERRAR_SESION'